import { TransactionStatus, TransactionType } from "../enums"
import { Amount, ClickRefs, TransactionPart, BasketProduct } from "../common"
import { ZWPIANATimezoneISO3166Alpha2CountryMap } from "@zwp/platform.common"
import { CustomParameter } from "../common/custom-parameter"

export interface TransactionResponse {
    id: string,
    dbCreatedAt: Date,
    dbUpdatedAt: Date,
    dbDeletedAt?: Date,
    awid: number,
    url: string,
    commissionSharingPublisherId?: number,
    commissionSharingSelectedRatePublisherId?: number,
    campaign?: string,
    siteName: string,
    commissionStatus: TransactionStatus,
    commissionAmount: Amount,
    saleAmount: Amount,
    ipHash: string,
    customerCountry: string,
    clickRefs?: ClickRefs,
    clickDate?: Date,
    transactionDate?: Date,
    validationDate?: Date,
    type: TransactionType,
    declineReason?: string,
    voucherCodeUsed: boolean,
    voucherCode?: string,
    lapseTime?: number,
    amended: boolean,
    amendReason?: string,
    oldSaleAmount?: Amount,
    oldCommissionAmount?: Amount,
    clickDevice?: string,
    transactionDevice?: string,
    customerAcquisition?: string,
    publisherUrl?: string,
    advertiserCountry: ZWPIANATimezoneISO3166Alpha2CountryMap,
    orderRef?: string,
    customParameters?: CustomParameter[],
    transactionParts?: TransactionPart[],
    paidToPublisher: boolean,
    paymentId?: number,
    transactionQueryId?: number,
    trackedCurrencyAmount?: Amount,
    originalSaleAmount?: Amount,
    advertiserCost?: Amount,
    basketProducts?: BasketProduct[],
    networkFee?: Amount,
    programmeId: string,
    programmeAwid: number,
    accountId: string,
    accountAwid: number
}