export enum LayoutElementConstraintType {
    WIDTH = "WIDTH",
    HEIGHT = "HEIGHT",
    MARGIN_TOP = "MARGIN_TOP",
    MARGIN_BOTTOM = "MARGIN_BOTTOM",
    MARGIN_LEFT = "MARGIN_LEFT",
    MARGIN_RIGHT = "MARGIN_RIGHT",
    PADDING_TOP = "PADDING_TOP",
    PADDING_BOTTOM = "PADDING_BOTTOM",
    PADDING_LEFT = "PADDING_LEFT",
    PADDING_RIGHT = "PADDING_RIGHT",
    CORNER_RADIUS = "CORNER_RADIUS"
}