export enum LoyaltyCardPaginatedListComponentContext {
    LOYALTY_CARD_LIST = 'LOYALTY_CARD_LIST',
    MERCHANT_DETAIL = 'MERCHANT_DETAIL',
    BRAND_DETAIL = 'BRAND_DETAIL',
    LOYALTY_CARD_SCHEME_DETAIL = 'LOYALTY_CARD_SCHEME_DETAIL',
    ENDUSER_DETAIL = 'ENDUSER_DETAIL'
}