const CDP_USERS_ACTION_IDENTIFIER = 'CDPUsers'

const ADMIN_USER_STATE_FEATURE_KEY = 'AdminUser'
const ADMIN_USER_ACTIVITY_STATE_FEATURE_KEY = 'AdminUserActivity'
const ADMIN_USER_CREDENTIAL_STATE_FEATURE_KEY = 'AdminUserCredential'
const ADMIN_USER_DEVICE_STATE_FEATURE_KEY = 'AdminUserDevice'
const ADMIN_USER_EMAIL_STATE_FEATURE_KEY = 'AdminUserEmail'
const ADMIN_USER_PHONE_STATE_FEATURE_KEY = 'AdminUserPhone'
const ADMIN_USER_SESSION_STATE_FEATURE_KEY = 'AdminUserSession'

const ENDUSER_STATE_FEATURE_KEY = 'Enduser'
const ENDUSER_ACTIVITY_STATE_FEATURE_KEY = 'EnduserActivity'
const ENDUSER_ADDRESS_STATE_FEATURE_KEY = 'EnduserAddress'
const ENDUSER_CREDENTIAL_STATE_FEATURE_KEY = 'EnduserCredential'
const ENDUSER_DEVICE_STATE_FEATURE_KEY = 'EnduserDevice'
const ENDUSER_EMAIL_STATE_FEATURE_KEY = 'EnduserEmail'
const ENDUSER_PHONE_STATE_FEATURE_KEY = 'EnduserPhone'
const ENDUSER_SESSION_STATE_FEATURE_KEY = 'EnduserSession'

export const Identifiers = {
    CDP_USERS_ACTION_IDENTIFIER,
    ADMIN_USER_STATE_FEATURE_KEY,
    ADMIN_USER_ACTIVITY_STATE_FEATURE_KEY,
    ADMIN_USER_CREDENTIAL_STATE_FEATURE_KEY,
    ADMIN_USER_DEVICE_STATE_FEATURE_KEY,
    ADMIN_USER_EMAIL_STATE_FEATURE_KEY,
    ADMIN_USER_PHONE_STATE_FEATURE_KEY,
    ADMIN_USER_SESSION_STATE_FEATURE_KEY,
    
    ENDUSER_STATE_FEATURE_KEY,
    ENDUSER_ACTIVITY_STATE_FEATURE_KEY,
    ENDUSER_ADDRESS_STATE_FEATURE_KEY,
    ENDUSER_CREDENTIAL_STATE_FEATURE_KEY,
    ENDUSER_DEVICE_STATE_FEATURE_KEY,
    ENDUSER_EMAIL_STATE_FEATURE_KEY,
    ENDUSER_PHONE_STATE_FEATURE_KEY,
    ENDUSER_SESSION_STATE_FEATURE_KEY
}