const REWARDS_NETWORK_TILLO_ACTION_IDENTIFIER = 'RewardsNetworkTillo'

const BRAND_STATE_FEATURE_KEY = 'Brand'
const DIGITAL_CODE_STATE_FEATURE_KEY = 'DigitalCode'
const DIGITAL_CODE_BRAND_STATE_FEATURE_KEY = 'DigitalCodeBrand'
const FLOAT_STATE_FEATURE_KEY = 'Float'
const STORE_CARD_FEATURE_KEY = 'StoreCard'
const TRANSACTION_SPREAD_FEATURE_KEY = 'TransactionSpread'

export const Identifiers = {
    REWARDS_NETWORK_TILLO_ACTION_IDENTIFIER,
    BRAND_STATE_FEATURE_KEY,
    DIGITAL_CODE_STATE_FEATURE_KEY,
    DIGITAL_CODE_BRAND_STATE_FEATURE_KEY,
    FLOAT_STATE_FEATURE_KEY,
    STORE_CARD_FEATURE_KEY,
    TRANSACTION_SPREAD_FEATURE_KEY
}