const FSN_TINK_ACTION_IDENTIFIER = 'FSNTink'

const ACCOUNT_STATE_FEATURE_KEY = 'Account'
const ACCOUNT_CONSENT_STATE_FEATURE_KEY = 'AccountConsent'
const CREDENTIAL_STATE_FEATURE_KEY = 'Credential'
const MERCHANT_STATE_FEATURE_KEY = 'Merchant'
const PROVIDER_STATE_FEATURE_KEY = 'Provider'
const PROVIDER_CONSENT_STATE_FEATURE_KEY = 'ProviderConsent'
const TOKEN_STATE_FEATURE_KEY = 'Token'
const TRANSACTION_STATE_FEATURE_KEY = 'Transaction'
const USER_STATE_FEATURE_KEY = 'User'
const WEBHOOK_ENDPOINT_STATE_FEATURE_KEY = 'WebhookEndpoint'

export const Identifiers = {
    FSN_TINK_ACTION_IDENTIFIER,
    ACCOUNT_STATE_FEATURE_KEY,
    ACCOUNT_CONSENT_STATE_FEATURE_KEY,
    CREDENTIAL_STATE_FEATURE_KEY,
    MERCHANT_STATE_FEATURE_KEY,
    PROVIDER_STATE_FEATURE_KEY,
    PROVIDER_CONSENT_STATE_FEATURE_KEY,
    TOKEN_STATE_FEATURE_KEY,
    TRANSACTION_STATE_FEATURE_KEY,
    USER_STATE_FEATURE_KEY,
    WEBHOOK_ENDPOINT_STATE_FEATURE_KEY
}