export enum LoggableEnduserActionType {
    ENDUSER_SESSION_REGISTER = "ENDUSER_SESSION_REGISTER",
    ENDUSER_SESSION_LOGIN = "ENDUSER_SESSION_LOGIN",
    ENDUSER_SESSION_LOGOUT_CURRENT = "ENDUSER_SESSION_LOGOUT_CURRENT",
    ENDUSER_SESSION_LOGOUT_ALL = "ENDUSER_SESSION_LOGOUT_ALL",
    ENDUSER_SESSION_LOGOUT_BY_ID = "ENDUSER_SESSION_LOGOUT_BY_ID",
    ENDUSER_SESSION_REFRESH_CLOSE = "ENDUSER_SESSION_REFRESH_CLOSE",
    ENDUSER_SESSION_REFRESH_OPEN = "ENDUSER_SESSION_REFRESH_OPEN"
}