export enum LoggableAdminUserActionType {
    ADMIN_USER_SESSION_REGISTER = "ADMIN_USER_SESSION_REGISTER",
    ADMIN_USER_SESSION_LOGIN = "ADMIN_USER_SESSION_LOGIN",
    ADMIN_USER_SESSION_LOGOUT_CURRENT = "ADMIN_USER_SESSION_LOGOUT_CURRENT",
    ADMIN_USER_SESSION_LOGOUT_ALL = "ADMIN_USER_SESSION_LOGOUT_ALL",
    ADMIN_USER_SESSION_LOGOUT_BY_ID = "ADMIN_USER_SESSION_LOGOUT_BY_ID",
    ADMIN_USER_SESSION_REFRESH_CLOSE = "ADMIN_USER_SESSION_REFRESH_CLOSE",
    ADMIN_USER_SESSION_REFRESH_OPEN = "ADMIN_USER_SESSION_REFRESH_OPEN"
}