// import {
//     MakeHexWithHSLSaturation,
//     MakeHexWithHSVSaturation} from './color.utils'
// import { ZWPScrollAxisAlignment } from "../model/scrolling/zwp.scroll-axis.alignment";
// import { stringUnionToArray } from "./primitive-type.utils";

// const baseHex = '#23101b'
// console.log(baseHex, 'BASE COLOR')

// const scrollAlignments = stringUnionToArray<ZWPScrollAxisAlignment>()('center', 'end', 'nearest', 'start')

// const hex0 = MakeHexWithLightness(baseHex, 0)
// const hex100 = MakeHexWithLightness(baseHex, 100)
// const hex200 = MakeHexWithLightness(baseHex, 200)
// const hex300 = MakeHexWithLightness(baseHex, 300)
// const hex400 = MakeHexWithLightness(baseHex, 400)
// const hex500 = MakeHexWithLightness(baseHex, 500)
// const hex600 = MakeHexWithLightness(baseHex, 600)
// const hex700 = MakeHexWithLightness(baseHex, 700)
// const hex800 = MakeHexWithLightness(baseHex, 800)
// const hex900 = MakeHexWithLightness(baseHex, 900)
// const hex1000 = MakeHexWithLightness(baseHex, 1000)

// console.log(hex0, 'hex0')
// console.log(hex100, 'hex100')
// console.log(hex200, 'hex200')
// console.log(hex300, 'hex300')
// console.log(hex400, 'hex400')
// console.log(hex500, 'hex500')
// console.log(hex600, 'hex600')
// console.log(hex700, 'hex700')
// console.log(hex800, 'hex800')
// console.log(hex900, 'hex900')
// console.log(hex1000, 'hex1000')

// const hexHSVSaturation0 = MakeHexWithHSVSaturation(baseHex, 0)
// const hexHSVSaturation10 = MakeHexWithHSVSaturation(baseHex, 10)
// const hexHSVSaturation20 = MakeHexWithHSVSaturation(baseHex, 20)
// const hexHSVSaturation30 = MakeHexWithHSVSaturation(baseHex, 30)
// const hexHSVSaturation40 = MakeHexWithHSVSaturation(baseHex, 40)
// const hexHSVSaturation50 = MakeHexWithHSVSaturation(baseHex, 50)
// const hexHSVSaturation60 = MakeHexWithHSVSaturation(baseHex, 60)
// const hexHSVSaturation70 = MakeHexWithHSVSaturation(baseHex, 70)
// const hexHSVSaturation80 = MakeHexWithHSVSaturation(baseHex, 80)
// const hexHSVSaturation90 = MakeHexWithHSVSaturation(baseHex, 90)
// const hexHSVSaturation100 = MakeHexWithHSVSaturation(baseHex, 100)

// const hexHSLSaturation0 = MakeHexWithHSLSaturation(baseHex, 0)
// const hexHSLSaturation10 = MakeHexWithHSLSaturation(baseHex, 10)
// const hexHSLSaturation20 = MakeHexWithHSLSaturation(baseHex, 20)
// const hexHSLSaturation30 = MakeHexWithHSLSaturation(baseHex, 30)
// const hexHSLSaturation40 = MakeHexWithHSLSaturation(baseHex, 40)
// const hexHSLSaturation50 = MakeHexWithHSLSaturation(baseHex, 50)
// const hexHSLSaturation60 = MakeHexWithHSLSaturation(baseHex, 60)
// const hexHSLSaturation70 = MakeHexWithHSLSaturation(baseHex, 70)
// const hexHSLSaturation80 = MakeHexWithHSLSaturation(baseHex, 80)
// const hexHSLSaturation90 = MakeHexWithHSLSaturation(baseHex, 90)
// const hexHSLSaturation100 = MakeHexWithHSLSaturation(baseHex, 100)

// console.log('Sat 0', `HSL ${hexHSLSaturation0}`, '|', `HSV ${hexHSVSaturation0}`)
// console.log('Sat 10', `HSL ${hexHSLSaturation10}`, '|', `HSV ${hexHSVSaturation10}`)
// console.log('Sat 20', `HSL ${hexHSLSaturation20}`, '|', `HSV ${hexHSVSaturation20}`)
// console.log('Sat 30', `HSL ${hexHSLSaturation30}`, '|', `HSV ${hexHSVSaturation30}`)
// console.log('Sat 40', `HSL ${hexHSLSaturation40}`, '|', `HSV ${hexHSVSaturation40}`)
// console.log('Sat 50', `HSL ${hexHSLSaturation50}`, '|', `HSV ${hexHSVSaturation50}`)
// console.log('Sat 60', `HSL ${hexHSLSaturation60}`, '|', `HSV ${hexHSVSaturation60}`)
// console.log('Sat 70', `HSL ${hexHSLSaturation70}`, '|', `HSV ${hexHSVSaturation70}`)
// console.log('Sat 80', `HSL ${hexHSLSaturation80}`, '|', `HSV ${hexHSVSaturation80}`)
// console.log('Sat 90', `HSL ${hexHSLSaturation90}`, '|', `HSV ${hexHSVSaturation90}`)
// console.log('Sat 100', `HSL ${hexHSLSaturation100}`, '|', `HSV ${hexHSVSaturation100}`)

// const p1redRGB80: RGBColor = HexToRGB(redHex80)
// const p1redHSV80: HSVColor = RGBToHSV(p1redRGB80)
// const p1redRGB80Res: RGBColor = HSVToRGB(p1redHSV80)
// const p1redHex80Res = RGBToHex(p1redRGB80Res)

// console.log('P1')
// console.log(p1redRGB80, 'p1redRGB80')
// console.log(p1redHSV80, 'p1redHSV80')
// console.log(p1redRGB80Res, 'p1redRGB80Res')
// console.log(p1redHex80Res, 'p1redHex80Res')

// const p2redRGB80: RGBColor = HexToRGB(redHex80)
// const p2redHSL80: HSLColor = RGBToHSL(p2redRGB80)
// const p2redRGB80Res: RGBColor = HSLToRGB(p2redHSL80)
// const p2redHex80Res = RGBToHex(p2redRGB80Res)

// console.log('')
// console.log('')
// console.log('P2')
// console.log(p2redRGB80, 'p2redRGB80')
// console.log(p2redHSL80, 'p2redHSL80')
// console.log(p2redRGB80Res, 'p2redRGB80Res')
// console.log(p2redHex80Res, 'p2redHex80Res')

// const p3redRGB80: RGBColor = HexToRGB(redHex80)
// const p3redHSV80: HSVColor = RGBToHSV(p3redRGB80)
// const p3redHSL80: HSLColor = HSVToHSL(p3redHSV80)
// const p3redRGB80Res: RGBColor = HSLToRGB(p3redHSL80)
// const p3redHex80Res = RGBToHex(p3redRGB80Res)

// console.log('')
// console.log('')
// console.log('P3')
// console.log(p3redRGB80, 'p3redRGB80')
// console.log(p3redHSV80, 'p3redHSV80')
// console.log(p3redHSL80, 'p3redHSL80')
// console.log(p3redRGB80Res, 'p3redRGB80Res')
// console.log(p3redHex80Res, 'p3redHex80Res')

// const p4redRGB80: RGBColor = HexToRGB(redHex80)
// const p4redHSL80: HSLColor = RGBToHSL(p4redRGB80)
// const p4redHSV80: HSVColor = HSLToHSV(p4redHSL80)
// const p4redRGB80Res: RGBColor = HSVToRGB(p4redHSV80)
// const p4redHex80Res = RGBToHex(p4redRGB80Res)

// console.log('')
// console.log('')
// console.log('P4')
// console.log(p4redRGB80, 'p4redRGB80')
// console.log(p4redHSL80, 'p4redHSL80')
// console.log(p4redHSV80, 'p4redHSV80')
// console.log(p4redRGB80Res, 'p4redRGB80Res')
// console.log(p4redHex80Res, 'p4redHex80Res')
