export type POINTER_EVENT_BUTTON_TYPE_PRIMARY = 0
export type POINTER_EVENT_BUTTON_TYPE_AUXILIARY = 1
export type POINTER_EVENT_BUTTON_TYPE_SECONDARY = 2
export type POINTER_EVENT_BUTTON_TYPE_BACK = 3
export type POINTER_EVENT_BUTTON_TYPE_FORWARD = 4

export enum PointerEventButtonType {
    POINTER_EVENT_BUTTON_TYPE_PRIMARY,
    POINTER_EVENT_BUTTON_TYPE_AUXILIARY,
    POINTER_EVENT_BUTTON_TYPE_SECONDARY,
    POINTER_EVENT_BUTTON_TYPE_BACK,
    POINTER_EVENT_BUTTON_TYPE_FORWARD
}