const CDP_PARTNER_NET_ACTION_IDENTIFIER = 'CDPPartnerNet'

const ASSET_STATE_FEATURE_KEY = 'Asset'
const LOCATION_STATE_FEATURE_KEY = 'Location'
const OFFER_PERSONALISATION_STATE_FEATURE_KEY = 'OfferPersonalisation'
const PARTNER_STATE_FEATURE_KEY = 'Partner'
const PARTNER_ASSET_ASSIGNMENT_STATE_FEATURE_KEY = 'PartnerAssetAssignment'
const PARTNER_ENDUSER_SUBSCRIPTION_STATE_FEATURE_KEY = 'PartnerEnduserSubscription'
const PARTNER_TYPE_STATE_FEATURE_KEY = 'PartnerType'
const PARTNER_TYPE_ASSIGNMENT_STATE_FEATURE_KEY = 'PartnerTypeAssignment'
const SUBGROUP_STATE_FEATURE_KEY = 'Subgroup'
const SUBGROUP_ASSET_ASSIGNMENT_STATE_FEATURE_KEY = 'SubgroupAssetAssignment'
const SUBGROUP_ENDUSER_SUBSCRIPTION_STATE_FEATURE_KEY = 'SubgroupEnduserSubscription'

export const Identifiers = {
    CDP_PARTNER_NET_ACTION_IDENTIFIER,
    ASSET_STATE_FEATURE_KEY,
    LOCATION_STATE_FEATURE_KEY,
    OFFER_PERSONALISATION_STATE_FEATURE_KEY,
    PARTNER_STATE_FEATURE_KEY,
    PARTNER_ASSET_ASSIGNMENT_STATE_FEATURE_KEY,
    PARTNER_ENDUSER_SUBSCRIPTION_STATE_FEATURE_KEY,
    PARTNER_TYPE_STATE_FEATURE_KEY,
    PARTNER_TYPE_ASSIGNMENT_STATE_FEATURE_KEY,
    SUBGROUP_STATE_FEATURE_KEY,
    SUBGROUP_ASSET_ASSIGNMENT_STATE_FEATURE_KEY,
    SUBGROUP_ENDUSER_SUBSCRIPTION_STATE_FEATURE_KEY,
}