const REWARDS_NETWORK_MERCHANT_NET_ACTION_IDENTIFIER = 'RewardsNetworkMerchantNet'

const ASSET_STATE_FEATURE_KEY = 'Asset'

const BRAND_STATE_FEATURE_KEY = 'Brand'
const CATEGORY_STATE_FEATURE_KEY = 'Category'

const INVOICE_STATE_FEATURE_KEY = 'Invoice'
const INVOICE_LINE_STATE_FEATURE_KEY = 'InvoiceLine'
const INVOICE_PAYMENT_STATE_FEATURE_KEY = 'InvoicePayment'

const LOCATION_STATE_FEATURE_KEY = 'Location'
const WEB_LOCATION_STATE_FEATURE_KEY = 'WebLocation'

const LOYALTY_CARD_SCHEME_STATE_FEATURE_KEY = 'LoyaltyCardScheme'
const LOYALTY_CARD_STATE_FEATURE_KEY = 'LoyaltyCard'
const LOYALTY_CARD_SCHEME_BRAND_STATE_FEATURE_KEY = 'LoyaltyCardSchemeBrand'

const MERCHANT_STATE_FEATURE_KEY = 'Merchant'

const OFFER_STATE_FEATURE_KEY = 'Offer'
const OFFER_LAYOUT_STATE_FEATURE_KEY = 'OfferLayout'
const OFFER_LAYOUT_ELEMENT_STATE_FEATURE_KEY = 'OfferLayoutElement'

const SECTOR_STATE_FEATURE_KEY = 'Sector'

// External Identifiers
const BRAND_TILLO_BRAND_STATE_FEATURE_KEY = 'BrandTilloBrand'

export const Identifiers = {
    REWARDS_NETWORK_MERCHANT_NET_ACTION_IDENTIFIER,
    
    ASSET_STATE_FEATURE_KEY,
    
    BRAND_STATE_FEATURE_KEY,
    CATEGORY_STATE_FEATURE_KEY,
    
    INVOICE_STATE_FEATURE_KEY,
    INVOICE_LINE_STATE_FEATURE_KEY,
    INVOICE_PAYMENT_STATE_FEATURE_KEY,
    
    LOCATION_STATE_FEATURE_KEY,
    WEB_LOCATION_STATE_FEATURE_KEY,
    
    LOYALTY_CARD_SCHEME_STATE_FEATURE_KEY,
    LOYALTY_CARD_STATE_FEATURE_KEY,
    LOYALTY_CARD_SCHEME_BRAND_STATE_FEATURE_KEY,
    
    MERCHANT_STATE_FEATURE_KEY,
    
    OFFER_STATE_FEATURE_KEY,
    OFFER_LAYOUT_STATE_FEATURE_KEY,
    OFFER_LAYOUT_ELEMENT_STATE_FEATURE_KEY,

    SECTOR_STATE_FEATURE_KEY,

    // External Identifiers
    BRAND_TILLO_BRAND_STATE_FEATURE_KEY
}