const PLATFORM_PRIVACY_ACTION_IDENTIFIER = 'PlatformPrivacy'

const IP_LOCATION_STATE_FEATURE_KEY = 'IPLocation'
const COOKIE_CONSENT_STATE_FEATURE_KEY = 'CookieConsent'

export const Identifiers = {
    PLATFORM_PRIVACY_ACTION_IDENTIFIER,
    IP_LOCATION_STATE_FEATURE_KEY,
    COOKIE_CONSENT_STATE_FEATURE_KEY
}