
const PLATFORM_FILES_ACTION_IDENTIFIER = 'PlatformFiles'

const FILE_DATA_STATE_FEATURE_KEY = 'FileData'
const FILE_EXPLORER_STATE_FEATURE_KEY = 'FileExplorer'

export const Identifiers = {
    PLATFORM_FILES_ACTION_IDENTIFIER,
    
    FILE_DATA_STATE_FEATURE_KEY,
    FILE_EXPLORER_STATE_FEATURE_KEY
}