const PLATFORM_GOOGLE_CLOUD_ACTION_IDENTIFIER = 'PlatformGoogleCloud'

const STORAGE_BUCKET_STATE_FEATURE_KEY = 'StorageBucket'
const STORAGE_OBJECT_STATE_FEATURE_KEY = 'StorageObject'
const FILE_UPLOAD_STATE_FEATURE_KEY = 'FileUpload'

export const Identifiers = {
    PLATFORM_GOOGLE_CLOUD_ACTION_IDENTIFIER,
    STORAGE_BUCKET_STATE_FEATURE_KEY,
    STORAGE_OBJECT_STATE_FEATURE_KEY,
    FILE_UPLOAD_STATE_FEATURE_KEY
}