const ZWP_ACTION_IDENTIFIER = 'ZWP'

const APPLICATION_STATE_FEATURE_KEY = 'Application'
const HISTORY_STORE_STATE_FEATURE_KEY = 'HistoryStore'
const KEYBOARD_STATE_FEATURE_KEY = 'Keyboard'
const PERSISTENCE_PROFILE_STATE_FEATURE_KEY = 'PersistenceProfile'
const PERSISTENCE_STATE_FEATURE_KEY = 'Persistence'
const ROUTER_STATE_FEATURE_KEY = 'Router'
const THEMING_STATE_FEATURE_KEY = 'Theming'

export const Identifiers = {
    ZWP_ACTION_IDENTIFIER,
    APPLICATION_STATE_FEATURE_KEY,
    HISTORY_STORE_STATE_FEATURE_KEY,
    KEYBOARD_STATE_FEATURE_KEY,
    PERSISTENCE_PROFILE_STATE_FEATURE_KEY,
    PERSISTENCE_STATE_FEATURE_KEY,
    ROUTER_STATE_FEATURE_KEY,
    THEMING_STATE_FEATURE_KEY
}