const REWARDS_NETWORK_AFFILIATE_WINDOW_ACTION_IDENTIFIER = 'RewardsNetworkAffiliateWindow'

const CATEGORY_STATE_FEATURE_KEY = 'Category'
const SECTOR_STATE_FEATURE_KEY = 'Sector'
const ACCOUNT_STATE_FEATURE_KEY = 'Account'

export const Identifiers = {
    REWARDS_NETWORK_AFFILIATE_WINDOW_ACTION_IDENTIFIER,
    CATEGORY_STATE_FEATURE_KEY,
    SECTOR_STATE_FEATURE_KEY,
    ACCOUNT_STATE_FEATURE_KEY,
}