const UKGOV_HMRC_ACTION_IDENTIFIER = 'UKGovHMRC'

const EIM32712_OCCUPATION_STATE_FEATURE_KEY = 'EIM32712Occupation'
const EIM32712_INDUSTRY_STATE_FEATURE_KEY = 'EIM32712Industry'

export const Identifiers = {
    UKGOV_HMRC_ACTION_IDENTIFIER,
    EIM32712_OCCUPATION_STATE_FEATURE_KEY,
    EIM32712_INDUSTRY_STATE_FEATURE_KEY
}