const FLOWS_ACTION_IDENTIFIER = 'Flows'
const FLOW_PROMPT_STATE_FEATURE_KEY = 'FlowPrompt'
const FLOW_CONTAINER_STATE_FEATURE_KEY = 'FlowContainer'
const FLOW_NODE_STATE_FEATURE_KEY = 'FlowNode'

export const Identifiers = {
    FLOWS_ACTION_IDENTIFIER,
    FLOW_PROMPT_STATE_FEATURE_KEY,
    FLOW_CONTAINER_STATE_FEATURE_KEY,
    FLOW_NODE_STATE_FEATURE_KEY
}

