const PLATFORM_LAYOUT_ACTION_IDENTIFIER = 'PlatformLayout'

const LAYOUT_STATE_FEATURE_KEY = 'Layout'
const PANEL_LAYOUT_STATE_FEATURE_KEY = 'PanelLayout'
const WINDOW_LAYOUT_STATE_FEATURE_KEY = 'WindowLayout'
const SNACKBAR_LAYOUT_STATE_FEATURE_KEY = 'SnackbarLayout'
const UTILITY_LAYOUT_STATE_FEATURE_KEY = 'UtilityLayout'
const MAIN_PANEL_STATE_FEATURE_KEY = 'MainPanel'
const TABLE_LAYOUT_STATE_FEATURE_KEY = 'TableLayout'

export const Identifiers = {
    PLATFORM_LAYOUT_ACTION_IDENTIFIER,
    LAYOUT_STATE_FEATURE_KEY,
    PANEL_LAYOUT_STATE_FEATURE_KEY,
    WINDOW_LAYOUT_STATE_FEATURE_KEY,
    SNACKBAR_LAYOUT_STATE_FEATURE_KEY,
    UTILITY_LAYOUT_STATE_FEATURE_KEY,
    MAIN_PANEL_STATE_FEATURE_KEY,
    TABLE_LAYOUT_STATE_FEATURE_KEY
}