export enum ZWPScreenBreakpointDevice {
    HANDSET_PORTRAIT = "HANDSET_PORTRAIT",
    HANDSET_LANDSCAPE = "HANDSET_LANDSCAPE",
    TABLET_PORTRAIT = "TABLET_PORTRAIT",
    TABLET_LANDSCAPE = "TABLET_LANDSCAPE",
    WEB_PORTRAIT = "WEB_PORTRAIT",
    WEB_LANDSCAPE = "WEB_LANDSCAPE"
}

export enum ZWPScreenBreakpointDeviceMinWidth {
    HANDSET_PORTRAIT = 0,
    HANDSET_LANDSCAPE = 0,
    TABLET_PORTRAIT = 600,
    TABLET_LANDSCAPE = 960,
    WEB_PORTRAIT = 840,
    WEB_LANDSCAPE = 1280
}

export enum ZWPScreenBreakpointDeviceMaxWidth {
    HANDSET_PORTRAIT = 599.98,
    HANDSET_LANDSCAPE = 959.98,
    TABLET_PORTRAIT = 839.98,
    TABLET_LANDSCAPE = 1279.98,
    WEB_PORTRAIT = Infinity,
    WEB_LANDSCAPE = Infinity
}