export enum BrowserPopupEventType {
    POPUPS_BLOCKED = 'POPUPS_BLOCKED',
    POPUP_ALREADY_EXISTS = 'POPUP_ALREADY_EXISTS',
    POPUP_UNABLE_TO_OPEN = 'POPUP_UNABLE_TO_OPEN',
    POPUP_OPEN = 'POPUP_OPEN',
    POPUP_CLOSE = 'POPUP_CLOSE',
    URL_CHANGE = 'URL_CHANGE',
    DATA_PUSH = 'DATA_PUSH'
}