const FSN_MASTERCARD_ACTION_IDENTIFIER = 'FSNMastercard'

// const ACCOUNT_STATE_FEATURE_KEY = 'Account'
// const CONSENT_STATE_FEATURE_KEY = 'Consent'
// const CREDENTIAL_STATE_FEATURE_KEY = 'Credential'
// const EVENT_STATE_FEATURE_KEY = 'Event'
// const MERCHANT_STATE_FEATURE_KEY = 'Merchant'
// const PROVIDER_STATE_FEATURE_KEY = 'Provider'
// const TOKEN_STATE_FEATURE_KEY = 'Token'
// const TRANSACTION_STATE_FEATURE_KEY = 'Transaction'
// const USER_STATE_FEATURE_KEY = 'User'

export const Identifiers = {
    FSN_MASTERCARD_ACTION_IDENTIFIER,
    // ACCOUNT_STATE_FEATURE_KEY,
    // CONSENT_STATE_FEATURE_KEY,
    // CREDENTIAL_STATE_FEATURE_KEY,
    // EVENT_STATE_FEATURE_KEY,
    // MERCHANT_STATE_FEATURE_KEY,
    // PROVIDER_STATE_FEATURE_KEY,
    // TOKEN_STATE_FEATURE_KEY,
    // TRANSACTION_STATE_FEATURE_KEY,
    // USER_STATE_FEATURE_KEY
}