const PLATFORM_DYNAMIC_QUERY_ACTION_IDENTIFIER = 'PlatformDynamicQuery'

const BOOLEAN_FILTER_STATE_FEATURE_KEY = 'BooleanFilter'
const DATE_FILTER_STATE_FEATURE_KEY = 'DateFilter'
const ENUM_FILTER_STATE_FEATURE_KEY = 'EnumFilter'
const NUMERIC_FILTER_STATE_FEATURE_KEY = 'NumericFilter'
const STRING_FILTER_STATE_FEATURE_KEY = 'StringFilter'
const UUID_FILTER_STATE_FEATURE_KEY = 'UUIDFilter'
const FILTER_GROUP_STATE_FEATURE_KEY = 'FilterGroup'
const STRUCTURED_QUERY_STATE_FEATURE_KEY = 'StructuredQuery'
const QUERYABLE_SCHEMA_TABLE_STATE_FEATURE_KEY = 'QueryableSchemaTable'
const QUERYABLE_SCHEMA_COLUMN_STATE_FEATURE_KEY = 'QueryableSchemaColumn'
const QUERYABLE_SCHEMA_RELATIONSHIP_STATE_FEATURE_KEY = 'QueryableSchemaRelationship'

export const Identifiers = {
    PLATFORM_DYNAMIC_QUERY_ACTION_IDENTIFIER,
    
    BOOLEAN_FILTER_STATE_FEATURE_KEY,
    DATE_FILTER_STATE_FEATURE_KEY,
    ENUM_FILTER_STATE_FEATURE_KEY,
    NUMERIC_FILTER_STATE_FEATURE_KEY,
    STRING_FILTER_STATE_FEATURE_KEY,
    UUID_FILTER_STATE_FEATURE_KEY,
    FILTER_GROUP_STATE_FEATURE_KEY,
    STRUCTURED_QUERY_STATE_FEATURE_KEY,
    QUERYABLE_SCHEMA_TABLE_STATE_FEATURE_KEY,
    QUERYABLE_SCHEMA_COLUMN_STATE_FEATURE_KEY,
    QUERYABLE_SCHEMA_RELATIONSHIP_STATE_FEATURE_KEY
}
